import { execFile } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import process from 'node:process'
import { promisify } from 'node:util'

const execFileAsync = promisify(execFile)

const rootDir = process.cwd()
const submoduleDir = resolve(rootDir, 'mixi2-api')
const outputFile = resolve(rootDir, 'src/generated/mixi2-api.ts')
const cliPath = resolve(rootDir, 'node_modules/openapi-typescript/bin/cli.js')
const candidateSpecPaths = [
  'openapi.yaml',
  'openapi.yml',
  'docs/openapi.yaml',
  'docs/openapi.yml',
  'api/openapi.yaml',
  'api/openapi.yml',
  'openapi/openapi.yaml',
  'openapi/openapi.yml',
  'schema/openapi.yaml',
  'schema/openapi.yml',
] as const

function findSpecPath(): string | null {
  for (const candidate of candidateSpecPaths) {
    const absolutePath = resolve(submoduleDir, candidate)
    if (existsSync(absolutePath)) {
      return absolutePath
    }
  }

  return null
}

async function generateTypes(specPath: string): Promise<void> {
  await mkdir(dirname(outputFile), { recursive: true })
  const { stdout } = await execFileAsync(
    process.execPath,
    [cliPath, specPath, '--alphabetize', '--default-non-nullable'],
    { maxBuffer: 10 * 1024 * 1024 },
  )

  const banner = [
    '/**',
    ' * This file is auto-generated from mixi2-api submodule.',
    ' * Do not edit this file directly.',
    ' */',
    '',
  ].join('\n')

  await writeFile(outputFile, `${banner}${stdout}`, 'utf8')
}

function ensureCliAvailable(): void {
  if (!existsSync(cliPath)) {
    throw new Error(
      [
        'openapi-typescript is not installed.',
        'Run `npm install` first and then retry `npm run generate:mixi2-types`.',
      ].join(' '),
    )
  }
}

async function main(): Promise<void> {
  if (!existsSync(submoduleDir)) {
    throw new Error(
      'mixi2-api submodule directory is missing. Run `git submodule update --init --recursive` first.',
    )
  }

  const specPath = findSpecPath()
  if (specPath == null) {
    throw new Error(
      [
        'OpenAPI schema was not found in mixi2-api submodule.',
        `Checked: ${candidateSpecPaths.join(', ')}`,
      ].join(' '),
    )
  }

  ensureCliAvailable()
  await generateTypes(specPath)

  const relativeSpecPath = relative(rootDir, specPath)
  const relativeOutputPath = relative(rootDir, outputFile)
  const generatedText = await readFile(outputFile, 'utf8')
  const lineCount = generatedText.split('\n').length

  console.log(`Generated ${relativeOutputPath} from ${relativeSpecPath} (${lineCount} lines).`)
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
