import { execFile } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdir, mkdtemp, readdir, rm, writeFile } from 'node:fs/promises'
import { dirname, extname, relative, resolve } from 'node:path'
import process from 'node:process'
import { tmpdir } from 'node:os'
import { promisify } from 'node:util'

const execFileAsync = promisify(execFile)

const rootDir = process.cwd()
const submoduleDir = resolve(rootDir, 'mixi2-api')
const protoRootDir = resolve(submoduleDir, 'proto')
const generatedDir = resolve(rootDir, 'src/generated/mixi2-api')
const outputFile = resolve(rootDir, 'src/generated/mixi2-api.ts')

async function ensureBufAvailable(): Promise<void> {
  try {
    await execFileAsync('buf', ['--version'], { maxBuffer: 1024 * 1024 })
  } catch {
    throw new Error(
      [
        '`buf` command was not found.',
        'Install Buf first: https://buf.build/docs/cli/installation/',
      ].join(' '),
    )
  }
}

function toPosixPath(path: string): string {
  return path.split('\\').join('/')
}

async function collectTypeScriptFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = await Promise.all(
    entries.map(async (entry): Promise<string[]> => {
      const absolutePath = resolve(dir, entry.name)
      if (entry.isDirectory()) {
        return collectTypeScriptFiles(absolutePath)
      }
      if (!entry.isFile()) {
        return []
      }
      if (extname(entry.name) !== '.ts') {
        return []
      }
      if (entry.name === 'index.ts') {
        return []
      }
      return [absolutePath]
    }),
  )

  return files.flat()
}

async function generateTypesFromProto(): Promise<void> {
  await mkdir(dirname(outputFile), { recursive: true })
  await rm(generatedDir, { recursive: true, force: true })

  const templateDir = await mkdtemp(resolve(tmpdir(), 'mixi2-api-types-'))
  const templatePath = resolve(templateDir, 'buf.gen.yaml')
  const outputRelativePath = toPosixPath(relative(rootDir, generatedDir))
  const template = [
    'version: v2',
    'plugins:',
    '  - remote: buf.build/bufbuild/es',
    `    out: ${outputRelativePath}`,
    '    opt:',
    '      - target=ts',
    '      - import_extension=none',
    '',
  ].join('\n')

  await writeFile(templatePath, template, 'utf8')

  try {
    await execFileAsync('buf', ['generate', protoRootDir, '--template', templatePath], {
      cwd: rootDir,
      maxBuffer: 10 * 1024 * 1024,
    })
  } finally {
    await rm(templateDir, { recursive: true, force: true })
  }
}

async function writeBarrelFile(): Promise<number> {
  const generatedFiles = await collectTypeScriptFiles(generatedDir)
  if (generatedFiles.length === 0) {
    throw new Error('No TypeScript files were generated from proto files.')
  }

  const exportLines = generatedFiles
    .map((absolutePath) => relative(dirname(outputFile), absolutePath))
    .map((path) => toPosixPath(path).replace(/\.ts$/u, ''))
    .sort((a, b) => a.localeCompare(b))
    .map((path) => `export * from './${path}'`)

  const banner = [
    '/**',
    ' * This file is auto-generated from mixi2-api proto definitions.',
    ' * Do not edit this file directly.',
    ' */',
    '',
  ].join('\n')

  await writeFile(outputFile, `${banner}${exportLines.join('\n')}\n`, 'utf8')
  return generatedFiles.length
}

async function main(): Promise<void> {
  if (!existsSync(submoduleDir)) {
    throw new Error(
      'mixi2-api submodule directory is missing. Run `git submodule update --init --recursive` first.',
    )
  }
  if (!existsSync(protoRootDir)) {
    throw new Error(
      `Proto directory is missing: ${relative(rootDir, protoRootDir)}. Run \`git submodule update --init --recursive\` first.`,
    )
  }

  await ensureBufAvailable()
  await generateTypesFromProto()
  const generatedCount = await writeBarrelFile()

  const relativeOutputPath = relative(rootDir, outputFile)
  const relativeGeneratedDir = relative(rootDir, generatedDir)
  console.log(
    `Generated ${generatedCount} TypeScript files in ${relativeGeneratedDir} and wrote barrel exports to ${relativeOutputPath}.`,
  )
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
